### ISSUE TITLE
Improve Symbol

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#154]
_From [ja...@overton.ca](https://code.google.com/u/114329883251282963390/) on March 08, 2014 15:29:53_

Improve textual definition and example of use for IAO_0000028 "symbol":

- change textual definition: An information content entity that is a mark or character used as a conventional representation of another entity.
- change definition source: based on Oxford English Dictionary
- example of usage: A written proper name such as "OBI"; a serial number such as "12324X"; a stop sign.
- change status: ready for release

See OBI Core review notes for discussion: https://docs.google.com/document/d/1Iv5VS8kbOnoQbBTt-FaJU37gK9MXkENm7pHGSk_q4d0/edit?usp=sharing

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=154_

**Comment by zhengj2007** [comment]
_From [alanruttenberg@gmail.com](https://code.google.com/u/alanruttenberg@gmail.com/) on March 10, 2014 21:54:26_

There has been quite a bit of discussion on the OBI and IAO list as well as off list (despite my preference). I've asked Mathias, who has recently been active in the discussion to collect the parts and organize them on the wiki page https://code.google.com/p/information-artifact-ontology/wiki/IAO_0000028_aka_symbol

**Comment by zhengj2007** [comment]
_From [MBrochhausen@gmail.com](https://code.google.com/u/MBrochhausen@gmail.com/) on March 27, 2014 07:37:42_

By and large I think that this is a huge step forward. There are two issues:
- what is a mark? Is it the same as a sign (in the semiotic meaning)? Is that what we mean? (It would be what I think should be there.
- this is probably based on the fact that I am not a native speaker: by saying that it is "a mark or character" do we say it is exactly one (which is not the case for 1234x? Is the "or" a union or a disjunction (I assume a union)?

Not big issues, you see. THis, again, is pretty agreeable.

**Comment by zhengj2007** [comment]
_From [ja...@overton.ca](https://code.google.com/u/114329883251282963390/) on March 27, 2014 08:18:21_

Thanks Mathias,

2. Alan also raised this point about multiple characters. In the OED they follow with the example: "e.g. the letter or letters standing for a chemical element or a character in musical notation. the symbol r in Figure 5 represents a gene which is ineffective. the chemical symbol for helium is He." So they want multiple characters, and our examples of use show that we intend multiple characters. But I agree that the proposed definition does not yet make that clear.

The simplest revision that could possibly work: "marks(s) or characters(s)".

Of course, this allows the pathological case of the multiple characters in a full paragraph or book from counting as one symbol. This raises a classic problem of vagueness that we can't hope to solve here in any satisfactory way. I don't think we should try.

1. "Sign" is not yet in IAO and I'm worried that it would be even harder to define than "symbol". "Mark" is not as burdened by theory. I was toying with the idea of adding terms from the theory behind Unicode (graphemes, glyphs, maybe code points), but that's another can of worms.

I would like to fix (2) and set (1) aside for future work with an editor note.

**Comment by zhengj2007** [comment]
_From [MBrochhausen@gmail.com](https://code.google.com/u/MBrochhausen@gmail.com/) on March 27, 2014 10:06:04_

James,

I completely agree. Let's fix (2) and set (1) aside.

**Comment by zhengj2007** [comment]
_From [ja...@overton.ca](https://code.google.com/u/114329883251282963390/) on March 31, 2014 09:17:35_

Decided on the OBI/IAO call 2014-03-31:

Revised textual definition: "An information content entity that is a mark(s) or character(s) used as a conventional representation of another entity."

Add editor note saying that we would like a deeper analysis of "mark" and "sign" in the future.

James will make this change when he has time.

**Comment by zhengj2007** [comment]
_From [ja...@overton.ca](https://code.google.com/u/114329883251282963390/) on April 10, 2014 12:36:36_

Fixed by commit 666 (how ominous!)

**Status:** Fixed

**Comment by StroemPhi** [comment]
> Fixed by commit 666 (how ominous!)

Haha, the devil and the detail, so true.
