### ISSUE TITLE
definition for algorithm needs to be made more precise

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#167]
_From [wddun...@gmail.com](https://code.google.com/u/106653010360062214642/) on April 10, 2014 10:05:28_

The definition for algorithm reads:

A plan specification which describes inputs, output of mathematical functions as well as workflow of execution for achieving an predefined objective. Algorithms are realized usually by means of implementation as computer programs for execution by automata.

However, it is not clear in the definition that output is a result of transforming the input in way described by the workflow. I suggest changing definition to:

A plan specification that describes the workflow for transforming the input to a mathematical function into an output, and this output is a predefined objective for the algorithm.

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=167_

**Comment by zhengj2007** [comment]
_From [ja...@overton.ca](https://code.google.com/u/114329883251282963390/) on April 10, 2014 12:48:53_

NOTE: In issue #156 we proposed to mark "algorithm" as "ready for release". Because of this issue I did not make that change. But once this issue is resolved I hope we can make that change.

**Comment by zhengj2007** [comment]
_From [wddun...@gmail.com](https://code.google.com/u/106653010360062214642/) on June 25, 2014 08:13:20_

This issue sounds like it is still open, but I haven't seen anymore chatter about it. Should it be closed?

**Comment by zhengj2007** [comment]
_From [james.ma...@gmail.com](https://code.google.com/u/105349588160612283402/) on July 04, 2014 06:12:34_

Can you remove the words 'plan specification' from the text definition, it's OntoSpeak. The rest I think is good:

An algorithm describes the workflow for transforming the input to a mathematical function into an output, and this output is a predefined objective for the algorithm.

**Labels:** -Priority-Medium Priority-High

**Comment by zhengj2007** [comment]
_From [ifo...@gmail.com](https://code.google.com/u/111675750791183175165/) on July 04, 2014 06:30:14_

James seems to be unaware of the reasons why 'plan specification' is used in IAO and OBI. 

The term is needed in order that the definition should have the proper definitional form

An A is a B which Cs

where B is the parent term of A in the ontology.
Without some parent term the definition does not work.
Do we have a definition of workflow?
Is 'mathematical function' not too narrow.
(Suppose e.g. we had a method for transforming mathematical theorems of certain sorts into proofs of such theorems. Would that not be an algorithm?)

Perhaps James is here defining 'algorithm specification' (a description, after all, is not an algorith, it is a description of an algorithm).

**Comment by zhengj2007** [comment]
_From [james.ma...@gmail.com](https://code.google.com/u/105349588160612283402/) on July 05, 2014 09:46:57_

Indeed Barry, i know of the reason I just don't agree. I don't think it is always necessary, though sometimes it is useful but in particular I definitely think it should not be included when the parent class is an ontological organisational class like plan specification. 

An algorithm is a collection of steps (workflow if you like) for transforming input to output - I will need help to see the distinction between the specification of these and the collection of these which is what you are calling algorithm specification and algorithm respectively I presume. (I do see the distinction between executing these in a process.) Consider:

"A + B = C"

Which of this is the algorithm specification and which is the algorithm?

**Comment by alanruttenberg** [comment]
"However, it is not clear in the definition that output is a result of transforming the input in way described by the workflow."

Not all algorithms define data <i>transformations</i>. For example, would you call an algorithm which describes how to take as input an ontology, and produce a boolean indicating whether it is consistent or not a "transformation"?

Regarding "algorithm" versus "algorithm specification", we only have "algorithm" in IAO.

The question of whether to use the genus in a definition or not keeps coming up, and I think it should be addressed independently of this case, so I propose we close this issue.
