### ISSUE TITLE
Version Name or Number

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#173]
_From [james.ma...@gmail.com](https://code.google.com/u/105349588160612283402/) on July 04, 2014 09:00:00_

Currently IAO has version number but this is too restrictive as some versions are named e.g. XP. Can this be reflected in the label and definition please? http://purl.obolibrary.org/obo/IAO_0000129

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=173_

**Comment by alanruttenberg** [comment]
I'm could fix the definition to not give the genus: "An information content entity which is a sequence of characters borne by part of each of a class of manufactured products or its packaging and indicates its order within a set of other products having the same name."

If I did that it should probably be done uniformly across all the definitions, and probably merits a discussion.

I'm not sure what to use for a label. Are you suggesting "version name"? The issue with using "version name" would be that it isn't uncommon to have both a number (or something like it) and a descriptive name, and this class is intended only for the former.

Many things called version numbers aren't in fact numbers, for example 1.2.10, even though they are composed of numbers. "Version number" seems to be a term of art. We don't (and shouldn't) suggest that every term that is syntactically <adjective> <noun> should name a class that is_a <noun>. 

Can you elaborate on a use of "XP" in the way you intend? Do you mean as in "Windows XP". 

I think it would be reasonable to keep the current label, given that the definition doesn't constrain along the lines you are worried about, but I'm open to changing it if others think it really needs to be changed.

**Comment by alanruttenberg** [comment]
If you agree that we can do nothing here, please close the issue.
