### ISSUE TITLE
Definitions of "example of usage" is truncated

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#180]
_From [rlwalls2...@gmail.com](https://code.google.com/u/114225325211762659400/) on March 24, 2015 11:54:08_

Using the latest version of ontology-metadata.owl from IAO, it looks like the definitions of example of usage ( http://purl.obolibrary.org/obo/IAO_0000112 ) is cut off. It just ends with the word not:

"A phrase describing how a class name should be used. May also include other kinds of examples that facilitate immediate understanding of a class semantics, such as widely known prototypical subclasses or instances of the class. Although essential for high level terms, examples for low level terms (e.g., Affymetrix HU133 array) are not"

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=180_

**Comment by zhengj2007** [comment]
_From [zhengj2...@gmail.com](https://code.google.com/u/100840849128868144328/) on March 24, 2015 10:05:57_

Thanks for report. I checked the IAO. The definition of 'example of usage' is exactly same as what it is now from the first release of IAO dated on Nov 2, 2009. Any suggestion to improve it?

Jie

**Comment by zhengj2007** [comment]
_From [rlwalls2...@gmail.com](https://code.google.com/u/114225325211762659400/) on March 24, 2015 13:59:16_

I think just finishing the sentence will work! Also, I think the definitions should say "term" rather than "class name" because 1) example of usage has been used a lot with object properties as well as classes, and 2) It is about how the property/class is used rather than how the name is used.

How about:

"A phrase describing how a term should be used. May also include other kinds of examples that facilitate immediate understanding of a class semantics, such as widely known prototypical subclasses or instances of the class. Although essential for high level terms, examples for low level terms (e.g., Affymetrix HU133 array) are not necessary."

On the other hand, is it correct that this annotation property is being used with object properties? I don't see why it should not be.

**Comment by alanruttenberg** [comment]
I have edited this in the source and it should appear in a future release. I removed the last sentence because I don't believe it to be true. Even terms such as Affymetrix HU133 array could use a citation of a paper in which the term is used.

**Comment by alanruttenberg** [comment]
Now; "A phrase describing how a term should be used and/or a citation to a work which uses it. May also include other kinds of examples that facilitate immediate understanding, such as widely know prototypes or instances of a class, or cases where a relation is said to hold."

**Comment by alanruttenberg** [comment]
As in many cases the clarification should be split out from the definition into an editor note. Another time.
