### ISSUE TITLE
proposed extensions to IAO:'document part' and IAO:'textual entity'

### ISSUE THREAD

**Issue by bill-baumgartner** [information-artifact-ontology/IAO#183]
Hello,

The attached patch file contains proposed extensions to the IAO:'document part' and IAO:'textual entity' sub-hierarchies. This work resulted from an examination of section headings in articles in the PubMed Central Open Access subset. New classes for document parts (and accompanying textual entity classes where applicable) include:
- abbreviations section
- author information section
- author summary section
- availability section
- case report section
- conclusion section
- conflict of interest section
- consent section
- ethical approval section
- figures section
- funding source declaration section
- future directions section
- genome announcement section
- keywords section
- materials section
- notes section
- patients section
- pre-publication history section
- related work section
- requirements section
- statistical analysis section
- study limitations section
- tables section

Also included in the patch are several alternative term suggestions for some previously defined classes:
- acknowledgements section
- author contributions section
- supplementary material to a document
- methods section
- results section
- introduction to a publication about an investigation
- discussion section of a publication about an investigation

All proposed classes include a definition, example of usage, editor preferred term, label, and term editor. Some also contain alternative terms. I hope you find that these suggestions meet the criteria for inclusion in the IAO. Please let me know if any changes are necessary.

Best,
Bill Baumgartner

[proposed_extenstions_to_document_part_and_textual_entity.patch.txt](https://github.com/information-artifact-ontology/IAO/files/147166/proposed_extenstions_to_document_part_and_textual_entity.patch.txt)

**Comment by KevinBretonnelCohen** [comment]
I second the request.

**Comment by alanruttenberg** [comment]
I will send a note to the developer list asking if there are any comments or objections, and in two weeks, assuming there are none, I will add these definitions.

**Comment by alanruttenberg** [comment]
Here is the note: https://groups.google.com/d/msg/information-ontology/IyYWAov71ZI/2QAjn2BUAQAJ

If you are interested in become an IAO committer, please contact me with your github id and I will add you.

**Comment by zhengj2007** [comment]
No objection. It's good to have these terms in IAO.

**Comment by wdduncan** [comment]
Seems fine to me.

**Comment by mcourtot** [comment]
Sounds good to me. Will there be some pattern for annotation properties, e.g. definitions etc? It would be good to homogenised this part of the ontology as this would be a significant addition.

**Comment by bill-baumgartner** [comment]
Thanks for moving this forward Alan. I'm not sure if I need to be a
committer at this stage, however if you feel that is appropriate my github
id is bill-baumgartner.

Regarding the question about a pattern for annotation properties, I tried
to be consistent with other classes in the IAO. If there are things that
are missing or need to be revised please let me know and I would be happy
to address them.

Best,
Bill

**Comment by alanruttenberg** [comment]
Hi Bill,
I added you to the group. You can take advantage of it when you see fit.
The WIP of merging is in the branch merge-document-parts. Next step is to assign IAO purls. I have some script to do that, and I'll get to it asap.

I had a question. All (most?) of the terms come in pairs: section and textual entity. I was wondering what your rational the duplication was. What do you see as differentiating the section from the textual entity? 

Arguably there shouldn't be a hard line, and some of the existing definitions of document parts have the flavor of textual entity definitions. 

One way to think about the question is: If the textual entity is one part of the section, what are the other parts? Perhaps adding something along those lines would help with better distinguishing the two. 

One way to handle this would be to defined a document part as anything that is part of a document - a defined class. Then, textual entities might be also classified as document parts, but one wouldn't need to assert that they were subclasses of both, something we try to avoid.

Alan

**Comment by StroemPhi** [comment]
Couldn't this issue also be closed, considering the fact that these new terms are in the current release (e.g. see [here](https://www.ebi.ac.uk/ols/ontologies/iao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000606&lang=en&viewMode=All&siblings=false)) and https://github.com/information-artifact-ontology/IAO/issues/187 having been closed?

**Comment by zhengj2007** [comment]
All request terms have been added.
