### ISSUE TITLE
object relation between a CRID and a continuant

### ISSUE THREAD

**Issue by cfrancois7** [information-artifact-ontology/IAO#185]
Dear everyone,
I'm working with many instances which have a CRID, a kind of classification but centralized.
I would like to know what kind of relation you use to establish the link between an instance and the CRID.
Do you use "has generic dependent at some time"? Or have you some more specific relationship such as "inheres in"?

Thank you.

**Comment by alanruttenberg** [comment]
Can you say which kind of relation you mean? I could interpret what you say as "the instances" meaning those things which the CRID identifies, or the piece of machinery which a CRID is stored with, or the pattern of electromagnetism that inhere in such a machine.

If you mean the targets of the CRID, for example if the CRID was a serial number that was being stamped on each of a manufactured car part, then  we would say there is an instance of CRID, that the instance of CRID is about the specific part instance, and that the part bears a quality which is a concretization of the CRID.
