### ISSUE TITLE
Class and relation for calculation datum

### ISSUE THREAD

**Issue by cfrancois7** [information-artifact-ontology/IAO#186]
Dear everyone,
I'm working to store calculation datum related to process.
Is there any improvement since [this discussion on ondotomachus' blog](https://odontomachus.wordpress.com/2014/03/30/aboutness-objects-propositions/)?

How do you resolve this problem with IAO in your sides? With data item?

Thanks you.

**Comment by alanruttenberg** [comment]
Calculation datum could be defined as eqivalent to any specific output of a [data transformation](http://purl.obolibrary.org/obo/OBI_0200000) as defined in [OBI](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0154556)
 
Would that capture your intention?
OBI deals with many processes related to data. Have you had a look at it?

**Comment by cfrancois7** [comment]
Yes, I resolve the approach with OBI.
