### ISSUE TITLE
disjoint axioms for occurrents

### ISSUE THREAD

**Issue by aellenhicks** [information-artifact-ontology/IAO#189]
The following classes are asserted as disjoint in IAO: 'process boundary', 'process', 'spaitiotemporal region', 'temporal region'.

I suggest moving this to BFO 2.0. It is causing the following problem.

UBERON bridge to BFO 2.0 has 'life cycle temporal coundary' as a descendent class of process, which is a problem since they are instantaneous and processes are not. Will flag this issue with UBERON also. However, I suggest moving these restrictions to BFO 2.0 to facilliate consistency checking. Arguably the UBERON folks should not have to use IAO to check the consistency of mappings to BFO.

**Comment by aellenhicks** [comment]
Issue in UBERON

https://github.com/obophenotype/uberon/issues/1258

**Comment by zhengj2007** [comment]
IAO using BFO 2 class only graz release. The disjoint axioms are defined in that version of BFO and missed in latest BFO2.0 release. Need to fix the issue in next BFO 2.0 release.

**Comment by alanruttenberg** [comment]
It doesn't hurt to reassert these here (since they are true) but I agree that BFO 2 should include the disjointness axioms. I'm closing this as it is a BFO, not an IAO issue.
