### ISSUE TITLE
The PATO classes 'mass' and 'length' are incorrectly asserted as subclasses of 'quality'

### ISSUE THREAD

**Issue by dillerm** [information-artifact-ontology/IAO#191]
I recently noticed this discrepancy in Apollo-SV, which imports http://purl.obolibrary.org/obo/iao.owl. In PATO, 'mass' is a subclass of 'physical quality', while 'length' is a subclass of '1-D extent'.

**Comment by alanruttenberg** [comment]
Have a look at the PATO hierarchy. Both [1-D extent](http://purl.obolibrary.org/obo/PATO_0001018) and [physical quality])http://purl.obolibrary.org/obo/PATO_0001708) are subclasses of Quality. A class that is subclass of something is subclass also of all the classes the something is subclass of. Or: is_a is transitive.

It is a common strategy, when one imports terms via MIREOT, that one asserts them as subclass of some other parent class, in the case that one doesn't want to also import all the superclasses. 

I'm closing this ticket, but will notice if you comment with further questions about this.
