### ISSUE TITLE
improve curation status coverage

### ISSUE THREAD

**Issue by mglont** [information-artifact-ontology/IAO#197]
The [curation status specification](http://purl.obolibrary.org/obo/IAO_0000078) consists of an enumeration of possible states including uncurated, requires discussion and ready for release. 

We would like to use this term, in conjunction with the [has curation status](http://purl.obolibrary.org/obo/IAO_0000114) qualifier to describe the curation status of [BioModels](http://www.ebi.ac.uk/biomodels) depositions. Like other public databases in life sciences, our content is versioned through periodic releases, so we would need to differentiate between terms that are ready for release and terms that have already been released.

Thus, it would make sense from our perspective to add a new term 'curated' with two children -- [ready for release](http://purl.obolibrary.org/obo/IAO_0000122) and 'released', which would also need to be created. The new terms would help represent the curation status state chart more faithfully:

![iao_0000078](https://user-images.githubusercontent.com/5095911/27283669-38d7cf72-54ed-11e7-8b12-8d8d6836c63a.PNG)

**Comment by mcourtot** [comment]
Hi @zhengj2007 - would you mind looking over this request please?

**Comment by zhengj2007** [comment]
@mcourtot Thanks for reminding me. Too busy to forget reply this issue.

@mglont Sorry for late reply.

All IAO curation status is instance. So, we cannot create an instance of an instance. Here are the curation statuses IAO defined from 'uncurated' to 'ready for release':
uncurated -> metadata incomplete -> metadata complete -> pending final vetting ->ready for release

All except 'uncurated' are considered as curated status. 
 
Here are details of these curation statuses: https://github.com/information-artifact-ontology/IAO/wiki/OntologyMetadata

I think IAO missed 'released' status. I am happy to add it in. Does it fit your needs?

**Comment by mglont** [comment]
Hi Jie,

Thanks for the feedback, it's very much appreciated! It'd definitely be useful to add 'released'.

**Comment by zhengj2007** [comment]
OK. I will add it and let you know when I am done.

**Comment by zhengj2007** [comment]
@mglont 'released' status has been added in ontology-metadata.owl. ID is: IAO_0000651.

commit: https://github.com/information-artifact-ontology/IAO/commit/0d1b88573ef1eb91779c6d6634f36323403cb88d
