### ISSUE TITLE
dc:member does not exist

### ISSUE THREAD

**Issue by tgbugs** [information-artifact-ontology/IAO#199]
what is wrong: Importing http://purl.obolibrary.org/obo/iao.owl results in `dc:member` being added as an annotation property.
why: Member is not defined for [dublin core elements](http://dublincore.org/documents/dces/). http://purl.org/dc/elements/1.1/member -> 404 error.
how to fix it: Remove [this line from ioa-merged.owl](https://github.com/information-artifact-ontology/IAO/blob/master/releases/2017-03-24/iao-merged.owl#L620). The underlying cause is not entirely clear to me, but it might be related to [this line in generate-obo.lisp](https://github.com/information-artifact-ontology/IAO/blob/master/src/tools/build/generate-obo.lisp#L153).

When importing http://purl.obolibrary.org/obo/iao.owl I noticed a spurious dublin core AnnotationProperty `dc:member`. As far as I can tell this is not a 'real' dublin core element. This is directly cauesd by `<owl:AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/member"/>` which occurs in [ioa-merged.owl on line 620](https://github.com/information-artifact-ontology/IAO/blob/master/releases/2017-03-24/iao-merged.owl#L620). I think that this is somehow being pulled in by [this line in generate-obo.lisp](https://github.com/information-artifact-ontology/IAO/blob/master/src/tools/build/generate-obo.lisp#L153), but I could be mistaken.

**Comment by alanruttenberg** [comment]
It's a bug from BFO. dc:member isn't mentioned in this repository except for the release. I fixed it https://github.com/BFO-ontology/BFO/commit/69754eff3f8ce0dff25b8219b06a19e8c5ebfa1f and it should be removed next time IAO uses a newly released BFO.

Until then it shouldn't hurt, since we declare it as an annotation property, though I agree it is objectionable.
