### ISSUE TITLE
New annotations proposed: "user interface label", ...

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [information-artifact-ontology/IAO#205]
In GenEpiO I have "user interface label" and "user interface definition" and "user interface help" annotations that one can include in a term, and they are geared for selection lists and user help display etc. in software. They usually end up being shorter, abbreviated and lay-oriented text rather than ontology labels and definitions that are designed to satisfy an ontology search engine or convey aristotelian logic. The original label and definition remain available for source attribution and reference and "deeper" help info in user interface if desired.  

Does this appeal? It seems to me these terms should be in IAO.  The main motivation for having these as annotations situated in an ontology rather than in an external term mapping system is that then all community users can get the benefit of centrally managed and recommended user-interface-oriented terms for their apps in a simple way. A further step to software standardization. (However a user would still have the ability to override such terms with their own customizations).

p.s. ui label is different from "editor preferred term" in that it addresses the tuning one does for user interfaces.

**Comment by zhengj2007** [comment]
@Public-Health-Bioinformatics 
There is separate repository "ontology-metadata" that discuss about the annotation properties used for an ontology term. So, will move the issue to that repository.

**Comment by zhengj2007** [comment]
This issue was moved to information-artifact-ontology/ontology-metadata#38
