### ISSUE TITLE
New annotation property - 'may be identical to'

### ISSUE THREAD

**Issue by dosumis** [information-artifact-ontology/IAO#207]
VFB is dealing with very large numbers of neuronal cell type terms from different sources. Increasingly we have evidence from papers or analysis suggesting that two separately defined terms may actually refer to the same type of neuron.  Where such assertions are uncertain, we would like to use an annotation property capture them. The resulting annotation axiom can then be further annotated with provenance info (reference, comment, curator, evidence type etc).  This approach will allow us to display potential mappings to users and to track evidence that may eventually be used to inform decisions to merge terms.  This is likely to be generally useful in cell ontology work given rapid advances in single cell biology.

**Comment by cmungall** [comment]
or just using skos?

**Comment by dosumis** [comment]
> or just using skos?

Do you have any particular SKOS property in mind?  I don't feel that any of the [SKOS mapping relations](https://www.w3.org/TR/skos-reference/#mapping)  quite work.  I actually think a realist way of describing the problem works well in this case:

Neurons types are natural types (Universal is too loaded).  There are multiple ways to uniquely identify a neuron type by some combination of the properties they have.  When we are truly confident that two or more terms, with different definitions, refer to the same type, then we will merge.  Until then we need to relate these terms in some way and track assertions & evidence that they refer to the same type.  See example here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/pull/347#issuecomment-420634805

    - A neuron type found in a screen for descending neurons has similar location and morphology to a neuron type found by a group studying octopaminergic neurons and another discovered by a group studying fruitless expression neurons.

SKOS, OTOH has mapping relations like this:

The property skos:closeMatch is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications. In order to avoid the possibility of "compound errors" when combining mappings across more than two concept schemes, skos:closeMatch is not declared to be a transitive property.

I'm not confident that the neuron types in the example could be used interchangeably in some information retrieval applications.  Either they are the same type or they are not, we're just not confident enough to say so yet.  Further experiments (an experiment assaying expression of the driver used find the descending neuron + fruitless / Octopaminergic neuron marker) are needed.

(I'm not completely dogmatic about this realist framing though.  We could decide by fiat that the descending neuron term covers all with that morphology, making the other two subclasses - but we'd still merge if all members of the class defined by morphology turned out to be fruitless expressing octopaminergic neurons)

**Comment by cmungall** [comment]
OK, seems new property is justified - do you want to make a PR, or are you doing these @zhengj2007 ?

**Comment by zhengj2007** [comment]
This issue was moved to information-artifact-ontology/ontology-metadata#40
