### ISSUE TITLE
Suggested repository clean up

### ISSUE THREAD

**Issue by jamesaoverton** [information-artifact-ontology/IAO#217]
These suggestions are low priority and I don't think they should delay the release of #215.

The changes in #215 include an `iao-all.owl` file that imports `iao-edit.owl` and `obsolete.owl`. I suggest just importing `obsolete.owl` into `iso-edit.owl` and eliminating `iao-all.owl`.

Since #211 ROBOT is used to build IAO. I believe that `src/tools` is no longer used and can be removed. I think that these two scripts for OntoFox can also be removed: `clean-ontofox-results.pl`, `get-ontofox-imports`.

I don't understand the purpose of `src/ontology/iao-examples.owl`. Would it be better in `src/examples/`?

I'm confused about copying RO and BFO bits to this repository during releases. I suggest that IAO should instead `owl:import` dated versions of these dependencies.

The `Makefile` adds a license annotation that should just be asserted in `iao-edit.owl`. Between these changes and those suggested in #216, the `Makefile` would be greatly simplified.

**Comment by zhengj2007** [comment]
MakeFile is added.
