### ISSUE TITLE
NTR: IAO:"Preferred root term" (mildly urgent)

### ISSUE THREAD

**Issue by matentzn** [information-artifact-ontology/IAO#221]
There is a new long-awaited OLS feature in the oven which allows us to configure the root terms of the displayed ontology. This will reduce confusion of which hierarchies actually "belong" to an ontology, and enable the proper display of ontologies that are not built on a complete isa-backbone (i.e. where some classes are connected only via part of and so on). 

The development branch currently (about to be merged) uses some homemade annotation property in the OLS namespace (something like https://www.ebi.ac.uk/ols/hasPreferredRootTerm); Terms that are annotated with this property will be displayed as roots. Since I expect this property to be widely deployed across OBO ontologies for display purposes, do you think IAO is a more appropriate home? Caveat: We should decide fairly quickly, to bot block the release of the feature. Thanks!

@cmungall @jamesaoverton @dosumis @zhengj2007 @simonjupp

**Comment by cmungall** [comment]
Hurrah!

I actually prefer human readable IRIs for things like this, but currently we are using numerics, just grab yourself a range in the idspace file and add this. Even if it's not in an IAO release we can still agree on the URI.

Note preferred root is not synonymous with 'belonging', so it would be good to have clear labels and definitions (I guess the semantics free IRIs are better here...)

**Comment by matentzn** [comment]
Once we agree this is roughly ok, even if it is not merged, we will start using the IRI (to unblock OLS Dev team). 
https://github.com/information-artifact-ontology/IAO/pull/222

**Comment by zhengj2007** [comment]
I am wondering whether we should add the new annotation property in the ontology-metadata.owl rather than iao.owl.
https://github.com/information-artifact-ontology/ontology-metadata

**Comment by matentzn** [comment]
Oh I didn’t know this file existed! Agreed!

**Comment by zhengj2007** [comment]
@matentzn Could you please add the term in this file:
https://github.com/information-artifact-ontology/ontology-metadata/blob/master/src/ontology/ontology-metadata-edit.owl

I can merge the change after you finish and may make the release in December.

**Comment by matentzn** [comment]
https://github.com/information-artifact-ontology/ontology-metadata/pull/45

Thanks @zhengj2007

**Comment by zhengj2007** [comment]
Request annotation, has ontology root term, has been added in with ID: IAO_0000700
