### ISSUE TITLE
Adding postal code/zip code representation

### ISSUE THREAD

**Issue by mbrochhausen** [information-artifact-ontology/IAO#226]
This is requested by the OBIB community.

Adding classes.

Add "identifier" from PNO (http://purl.obolibrary.org/obo/IAO_0020000)

Create "Postal code"
Superclass: identifier
Definition: "An identifier that denotes some postal delivery route, some aggregate of postal delivery routes or a geographical region and was created for the purpose of sorting and delivering mail."

Create "Postal delivery route"
Superclass: plan specification
Definition: "A plan specification that if realized, is realized by the delivery of mail to some facility or mailbox within some geographical region"

Create "zone improvement plan code"
alternative term "ZIP code"
Superclass: "postal code"
Definition: "A postal code that is used in the United States for the purpose of sorting and delivering mail, and that denotes some postal delivery route or some aggregate of postal delivery routes."

**Comment by zhengj2007** [comment]
The terms look good to me. 

If no objection in 2 weeks, I'd like to add the terms in IAO.

**Comment by zhengj2007** [comment]
@mbrochhausen The label of PNO (http://purl.obolibrary.org/obo/IAO_0020000) is 'proper name'. Do you want to relabel the term in PNO or do you want to relabel it as 'identifier' in IAO?

**Comment by mbrochhausen** [comment]
If I open PNO from the PURL the label is 'identifier' and 'proper name' is an alternative term. Which version of PNO are you pulling? Thanks

**Comment by zhengj2007** [comment]
Added in release 2020-06-09
