### ISSUE TITLE
Why not use imports?

### ISSUE THREAD

**Issue by aucampia** [information-artifact-ontology/IAO#229]
This ontology seems to not be importing other ontologies it uses like BFO but instead "duplicating" then, is there a reason for this? Could it be changed to use imports instead?

**Comment by jamesaoverton** [comment]
The [`iao-edit.owl`](https://github.com/information-artifact-ontology/IAO/blob/master/src/ontology/iao-edit.owl) file shows how IAO imports BFO and some external ontology terms into the editor's version of the ontology. When the main `iao.owl` file is prepared for release, all the [imports are merged](https://github.com/information-artifact-ontology/IAO/blob/master/Makefile#L75), [reasoning is done](https://github.com/information-artifact-ontology/IAO/blob/master/Makefile#L88), and the result is a single self-contained OWL file, sometimes called a ["full" release file](https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-2-full-required) in the OBO community.

OBO projects are starting to also publish ["base" release files](https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-1-base-required), which link to external terms without including them in the file. This might be what you're after. IAO doesn't yet publish a base file, but you could build one with ROBOT.

Full files and base files each have advantages for different applications.
