### ISSUE TITLE
IRI of term 'Unique Apollo Label'

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#230]
IAO included an annotation property,  'Unique Apollo Label', defined in APOLLO_SV with IRI:
http://purl.obolibrary.org/obo/apollo_sv.owl/APOLLO_SV_0000040

This IRI is not resolvable.

I have two questions:
1. Should IAO take the term?
2. If so, do we need to send the request to APOLLO_SV for assigning a resolvable IRI to the term?

@hoganwr Any comments on it? I think it is the term you added. Thanks!

**Comment by hoganwr** [comment]
I apologize profusely for that.

I recommend just removing the annotation(s) from the relevant classes.

Bill

**Comment by hoganwr** [comment]
And thus removing the annotation property from IAO altogether.

**Comment by zhengj2007** [comment]
Thanks @hoganwr I will remove it.
