### ISSUE TITLE
NTRs: document related publication

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#232]
[VEuPathDB](https://veupathdb.org) database needs following two terms to annotate the publication status.

Name | Value
-- | --
Label | published document
Definition | A document that is published such as in a journal.
Parent | IAO_0000310 document
Definition source | EFO_0001796 published

Name | Value
-- | --
Label | document  in preparation for publication
Definition | A document that is in preparation for submission to be published.
Parent | IAO_0000310 document
Definition source | EFO_0001795 in preparation

IAO:0000311 publication (http://purl.obolibrary.org/obo/IAO_0000311) 
Definition: "A document that has been accepted by a publisher".
However, IAO does not defined what is a publisher. So, it is not clear whether 'published document' is  IAO:0000311  publication?

Hi, Larry @LEHunter, You are the term editor of IAO:0000311. Do you have any comments on it? Thanks! 

The terms were submitted to OBI before. The related issue: https://github.com/obi-ontology/obi/issues/1091

**Comment by zhengj2007** [comment]
'journal article' is an example of 'published document'.

We have proposed to add 'publishing process' and use equivalent axiom to define 'published document'.

Proposed definition for 'publishing process':
Definition: A planned process of making information, such as literature, music, and software etc., available to the public for sale or for free.
Definition source: https://en.wikipedia.org/wiki/Publishing

'published document':
Definition: A document that is published such as in a journal.
Equivalent axiom: document and is_specified_output_of some 'publishing process'
(not require a publisher)

Any thoughts and comments @LEHunter? Thanks!

Jie

**Comment by cstoeckert** [comment]
Discussed on OBI/IAO call Nov. 9, 2020. Agree to move forward with a 'publishing process' that would enable defining parts of the publishing process and the ouputs. Would address publication status.

AI: Jie move ahead with creating 'publishing process' as defined above.

**Comment by zhengj2007** [comment]
Added 'publishing process' with ID: IAO_0000444

**Comment by zhengj2007** [comment]
Proposed to update IAO:0000311 'publication' (http://purl.obolibrary.org/obo/IAO_0000311)

- Definition: A document that is available to the public for sale or for free.

- Logical axiom (equivalent): document and is_specified_output_of only 'publishing process'

- Alternative term: published document

**Comment by zhengj2007** [comment]
Discussed on Nov 23, 2020 OBI call. Will make the changes and create pull request for Dr. Larry Hunter to review.

**Comment by LEHunter** [comment]
Is there a record of the discussion?  I couldn’t join, and have a concern about the apparent disconnect between the logical and English definitions.  An English definition that was similar to the logical one (e.g. “A document that has gone through a publication process”) would be better.

Larry

On Nov 23, 2020, at 8:07 AM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:



Discussed on Nov 23, 2020 OBI call. Will make the changes and create pull request for Dr. Larry Hunter to review.

**Comment by zhengj2007** [comment]
I changed the definition back to 'A document that is published such as in a journal.', which is agreed before. The one that fits the updated logical definition you proposed looks fine to me.

**Comment by zhengj2007** [comment]
@LEHunter How about this?

proposed definition for publication: "A document that has gone through a publishing process, such as journal article."

**Comment by LEHunter** [comment]
I like that better.  How about “A document that is the output of a publishing process.”  Then in "example of usage," you could list journal article, newspaper story, book, etc.

Larry



On Nov 23, 2020, at 8:18 AM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:



@LEHunter<https://github.com/LEHunter> How about this?

proposed definition for publication: "A document that has gone through a publishing process, such as journal article."

**Comment by zhengj2007** [comment]
Updated IAO_0000311 publication:
Definition: A document that is the output of a publishing process.
example of usage: journal article, newspaper story, book, etc.
alternative term: published document

Added term 'document in preparation for publication', assigned ID: IAO_0000445

**Comment by LEHunter** [comment]
I approve of the definition.

On Nov 23, 2020, at 1:54 PM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:



Updated IAO_0000311 publication:
Definition: A document that is the output of a publishing process.
example of usage: journal article, newspaper story, book, etc.
alternative term: published document

Added term 'document in preparation for publication', assigned ID: IAO_0000445

**Comment by zhengj2007** [comment]
Thanks @LEHunter

**Comment by zhengj2007** [comment]
The new term and updated 'publication' term are available in release 2020-12-09.
