### ISSUE TITLE
journal article should be a subclass of publication

### ISSUE THREAD

**Issue by cmungall** [information-artifact-ontology/IAO#233]
https://www.ebi.ac.uk/ols/ontologies/iao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000013

![image](https://user-images.githubusercontent.com/50745/96663065-bc9af180-1304-11eb-8f9d-0fce39e0ef11.png)

_A report that is published in a journal_

should be placed here:

![image](https://user-images.githubusercontent.com/50745/96662675-b22c2800-1303-11eb-989d-68a1415bd3e7.png)

_A document that has been accepted by a publisher_

I suppose we could be pedantic and say a journal article can be *accepted* without being *published*. We could get into interesting discussions about temporal states.

But IMHO this is all unintuitive. most people would expect to find article as a type of publication. We can formally defend this by either defining a publication as something *accepted* for being published in a journal or saying an article is *accepted and published*.

this is not urgent. I will likely use schema.org/bibo/fabio for categorizing publications as I don't need IAO's rigor here.

**Comment by zhengj2007** [comment]
+1

See related tracker: https://github.com/information-artifact-ontology/IAO/issues/232

**Comment by cstoeckert** [comment]
Discussed OBI/IAO November 9, 2020 call. This may be addressed by creating the 'publishing process' term that can be used to define a journal article as both a report and a publication.

**Comment by zhengj2007** [comment]
Add logical axiom: is_specified_output_of only 'publishing process'. 
'journal article' is inferred as publication now.

**Comment by alanruttenberg** [comment]
+ is_specified_output_of *some* 'publishing process' ? Or is the intention
that unpublished works written in the style of an article or a document
*intended* to be  submitted to a journal be covered by the term? If that
were the case then the *some* axiom wouldn't apply.
Alan

**Comment by zhengj2007** [comment]
I think the report written in the style of a journal article or intended to submit to a journal but not published  is not a journal article.

**Comment by alanruttenberg** [comment]
Ok, then it makes sense to add the some condition: 

is_specified_output_of some 'publishing process'

**Comment by zhengj2007** [comment]
The edits are shown in release 2020-12-09.
