### ISSUE TITLE
document part: proposed synonyms and new term

### ISSUE THREAD

**Issue by tb143** [information-artifact-ontology/IAO#234]
Hi,

As part of a biomedical literature NLP project, we have identified a number of new synonyms we would like to propose to the IAO:'document part' sub-hierarchy.  Each proposed synonym is used in a plurality of publications.  We also propose a new term that assists with determining whether a document part can be processed with text analytics.

SYNONYMS:

abbreviations section (IAO:0000606)
abbreviation and acronyms
abbreviations and acronyms
abbreviation list
definitions for abbreviations
non-standard abbreviations
nonstandard abbreviations
nonstandard abbreviations and acronyms

abstract (IAO:0000315)
precis

acknowledgements section (IAO:0000324)
acknowledgement
acknowledgment

author contributions section (IAO:0000323)
authors' contribution
authors' contributions
authors' roles
contributorship

author information section (IAO:0000607)
biographies
contributor information

availability section (IAO:0000611)
availability of data
data archiving
data availability
data availability statement
data sharing statement

conflict of interest section (IAO:0000616)
conflict of interests
conflicts of interest
declaration of competing interest
declaration of interest
declaration of interests
disclosure of conflict of interest
duality of interest
statement of interest
authors' disclosures of potential conflicts of interest
competing financial interests

discussion section of a publication about an investigation (IAO:0000319)
discussions

ethical approval section (IAO:0000620)
ethical requirements
ethics
ethics statement

footnote (IAO:0000325)
footnotes

Funding source declaration section (IAO:0000623)
financial support
grants
role of the funding source
study funding

future directions section (IAO:0000625)
outlook

introduction to a publication about an investigation (IAO:0000316)
overview

methods section (IAO:0000317)
method
experimental methods
methodology

references section (IAO:0000320)
literature cited
reference
references
reference list

supplementary material to a document (IAO:0000326
additional file
additional files
electronic supplementary material
electronic supplementary materials
supplemental data
supplemental material
supplementary data
supplementary files
supplementary information
supplementary materials

TERM:

Preferred Name: graphical abstract 
Synonym: visual abstract
Definition: A pictorial summary of the main findings described in the document.

Please let me know if you require any clarifications or further information.

Regards,
[Tim Beck](https://www2.le.ac.uk/departments/genetics/research/staff-research-interests/dr-tim-beck-1)
on behalf of the Leicester/Imperial biomedical literature NLP project co-led with [Joram Posma](https://www.imperial.ac.uk/people/j.posma11)

**Comment by zhengj2007** [comment]
We will add the synonyms to the terms per your request.

Regarding the new term request, I will add to the  OBI call's agenda holding at 12:00 PM EST on Nov. 9. Welcome to join the call. The [call in information](http://obi-ontology.org) can be found on the OBI website: http://obi-ontology.org

**Comment by cstoeckert** [comment]
Discussed on OBI/IAO Nov. 9, 2020, If we don't hear of concerns with the synonyms in two weeks we will go ahead and add them.

For graphical abstract, propose 'abstract' as the parent.

**Comment by zhengj2007** [comment]
Hi @tb143,  I added the term you request to a tab-delimited format file with some minor edits following OBO Foundry recommendations. Could you please review the document row 9?

https://github.com/information-artifact-ontology/IAO/blob/master/src/ontology/template/IAO_newTerms.tsv

Thanks!

**Comment by tb143** [comment]
Looks fine to me, thanks!

**Comment by zhengj2007** [comment]
Thanks @tb143. I will add the term in the IAO and let you know when the new release is made.

**Comment by zhengj2007** [comment]
The new term and synonyms are available in release 2020-12-09.
