### ISSUE TITLE
document part: proposed new terms (for the discussion on Nov 9, 2020)

### ISSUE THREAD

**Issue by cyang0128** [information-artifact-ontology/IAO#235]
@ddooley @zhengj2007 

### term label: “descriptive data section”
- definition
A part of a document that lists and defines data variables, describes data characteristics (e.g. missing data information) and any assumptions and simplifications made.
- definition source
https://www.equator-network.org/reporting-guidelines/prisma/
- suggested parent term if possible
n/a

### term label: “additional results section”
- definition
A part of a document that reports analyses other than main results of the study (e.g. subgroups analyses, adjusted analyses, sensitivity analyses, etc.)
- definition source
https://www.equator-network.org/reporting-guidelines/strobe/ 
https://www.equator-network.org/reporting-guidelines/consort/
https://www.equator-network.org/reporting-guidelines/prisma/
- suggested parent term if possible
“results section” (IAO:0000318)

### term label: “research participants section”
- definition: 
A part of a document that describes human subject(s) that participated in a study (e.g. inclusion & exclusion criteria, recruitment methods, reasons for non-participation, grouping and randomisation, methods of follow-up, etc.).
- definition source
https://www.equator-network.org/reporting-guidelines/consort/
https://www.equator-network.org/reporting-guidelines/strobe-nut/ 
https://www.equator-network.org/reporting-guidelines/prisma/
- notes:
This term could be a parent term of “patients section” (IAO: 0000635).

### term label: “measurement methods section”
- definition
A part of a document that describes details of data assessment methods (data measurement). 
- definition source
https://www.equator-network.org/reporting-guidelines/strobe/ 
- suggested parent term if possible
 “methods section” (IAO:0000317) for describing investigation method.

### term label: “research settings section”
- definition
A part of a document that describes the physical/social/cultural conditions around a research trial.
- definition source
https://www.ncbi.nlm.nih.gov/books/NBK262175/ 
- suggested parent term if possible
 n/a

### term label: “study bias section”
- definition
A part of a document that describes systematic error introduced into sampling or testing by selecting or encouraging one outcome or answer over others
- definition source
DOI: 10.1097/PRS.0b013e3181de24bc
- notes
Disjoint with “study limitations section” (IAO:0000631)

**Comment by zhengj2007** [comment]
@cyang0128 Thanks for the submission. Will add to next Monday call's agenda.

**Comment by cstoeckert** [comment]
Discussed on OBI/IAO Nov. 9, 2020 call. Note that study limitations are defined as "A part of a document about biases or short comings related to the study design and execution." so would not be disjoint. Could be a subtype.

**Comment by zhengj2007** [comment]
@cyang0128 I added the terms you request on a tab-delimited format with some minor edits following OBO Foundry recommendations. Could you please review the document rows 3 - 8?

https://github.com/information-artifact-ontology/IAO/blob/master/src/ontology/template/IAO_newTerms.tsv

Thanks!

**Comment by cyang0128** [comment]
Dear @zhengj2007, thanks a lot. I have checked the rows 3-8, everything is fine. I agree and thanks for your work!

**Comment by zhengj2007** [comment]
Thanks @cyang0128. I will add the terms in the IAO and let you know when the new release is made.

**Comment by zhengj2007** [comment]
The new terms are available in release 2020-12-09.
