### ISSUE TITLE
BFO 2020

### ISSUE THREAD

**Issue by luanfg** [information-artifact-ontology/IAO#247]
Is there any version of IAO that is updated to the latest version of BFO?

**Comment by zhengj2007** [comment]
Do you mean to update to BFO ISO?

IAO is using BFO 2.0 (classes only version) rather than BFO ISO, which includes temporal relations. Current most of OBO Foundry ontologies are using BFO class only version since there are some issues in using  temporal relations. So, IAO will not update to BFO ISO until the issues resolved and the OBO Foundry community decide to transform to it. The BFO 2.0 is the latest version of BFO classes only.

**Comment by luanfg** [comment]
Thank you for your quick response. I ask because the 2020 version seems to have new possibilities that are quite interesting, such as allowing a GDC to be concretized also by a process.

**Comment by alanruttenberg** [comment]
Actually, the issues are with the non-temporalized relations, which don't have any formal interpretation in BFO. Sorry, had to say...

@luanfg If you are interested in pursuing a BFO-2020 version, generally thinking about IAO, and making some changes, I'd be up for discussion about it and might be able to take some time to collaborate. We could fork an experimental version, see where it goes, and then possibly contribute back any interesting things we come up with. There's also room for there to be a BFO-2020 compatible version of IAO that is offered as a variant that some might be interested in using, particularly if they aren't integrating with a lot of other OBO ontologies. There's another IAO as well, in [CCO](https://github.com/CommonCoreOntology/CommonCoreOntologies), that mirrors a lot of IAO. I'd like to get them unified but even if not, they are committed to using BFO-2020 and some current work involves using CCO so I want to improve their version in any case.

**Comment by luanfg** [comment]
Hey @alanruttenberg , right now we have moved forward using BFO 2.0, but I'd be interested in working on a BFO-2020 version for future needs :)
I've reached the IAO version in CCO some time ago and it was very similar to this version. At the time I wasn't sure why they were in different repositories hehe.

Sorry for the month delay, for some reason I wasn't getting mail notifications from github.
