### ISSUE TITLE
Add "mentioned by" as inverse of "mentions" object property

### ISSUE THREAD

**Issue by ddooley** [information-artifact-ontology/IAO#250]
Due to our use of robot tables to associate instances with the data specifications they are associated with, it would be handy to have "mentioned by" as an inverse object property of "mentions". (We're dealing with enumerations where the enumeration has to stay looser about the kinds of things it references, so unable to use 'member of').

Is "mentioned by" better than "mentioned in"?  Technically X 'mentioned in' Y may convey the nuance that a component or part of Y is doing the denotation (the mentioning).

Shall I make a pull request for that?

**Comment by zhengj2007** [comment]
I'd like to check with @alanruttenberg since he is the term editor of 'mentions'.

Hi @alanruttenberg, How do you think to add "mentioned by" as an inverse object property of "mentions"? Thanks!

**Comment by alanruttenberg** [comment]
Fine by me. Not much difference in the naming but "mentioned by" slightly preferred.
