### ISSUE TITLE
Zip code

### ISSUE THREAD

**Issue by masciam** [information-artifact-ontology/IAO#254]
I am working on a geospatial use case for NIEHS and we would need a ZIP CODE term. I have look at the definition is in IAO "Term IRI: http://purl.obolibrary.org/obo/IAO_0000648
Definition: A postal code that is used in the United States for the purpose of sorting and delivering mail, and that denotes some postal delivery route or some aggregate of postal delivery routes."  and I would like to have some clarification 
We are using the zip code to identify a specific address ( geographical location)  and not for postal reason as the definition states.
Is there any way we could change the definition with one that will include the location information and not only linked to postal services?

**Comment by hoganwr** [comment]
This is exactly what a ZIP code is, as defined by the US Postal Service.

If you need ZIP Code Tabulation Areas, as created by the US Census Bureau,
that is an entirely different thing.  These things do in fact refer to
specific geographical regions.

A delivery ZIP can in fact and often does differ from a ZCTA.

The two are different, and should be distinguished.

**Comment by masciam** [comment]
Bill ,
Thanks for the reply.
The information store in the data are a ‘zip code’ but, what they really need is the geographical area. I think this is a misuse of the zip code in the geospatial studies.

I would need to link the zip code to the ZCTA. for what I know there is not a direct link.
I may try to create a link by using a GIS. I could not find a definition for ZCAT do you know if there is one ?

Thanks
AM


From: Bill Hogan ***@***.***>
Date: Friday, April 22, 2022 at 1:50 PM
To: information-artifact-ontology/IAO ***@***.***>
Cc: Anna Maria Masci ***@***.***>, Author ***@***.***>
Subject: Re: [information-artifact-ontology/IAO] Zip code (Issue #254)
This is exactly what a ZIP code is, as defined by the US Postal Service.

If you need ZIP Code Tabulation Areas, as created by the US Census Bureau,
that is an entirely different thing. These things do in fact refer to
specific geographical regions.

A delivery ZIP can in fact and often does differ from a ZCTA.

The two are different, and should be distinguished.

**Comment by hoganwr** [comment]
The Census bureau page on ZCTAs is here:
https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html

it says the following:

"ZIP Code Tabulation Areas (ZCTAs) are generalized areal representations of
United States Postal Service (USPS) ZIP Code service areas.

The USPS ZIP Codes identify the individual post office or metropolitan area
delivery station associated with mailing addresses. USPS ZIP Codes are not
areal features but a collection of mail delivery routes.

The term ZCTA was created to differentiate between this entity and true
USPS ZIP Codes.  ZCTA is a trademark of the U.S. Census Bureau; ZIP Code is
a trademark of the U.S. Postal Service."
