### ISSUE TITLE
Archive https://github.com/information-artifact-ontology/iao-releases

### ISSUE THREAD

**Issue by cmungall** [information-artifact-ontology/IAO#258]
I assume this repo is no longer used. I don't know why it was created. Maybe this is just from historic releases pre github?

It should be archived and the README updated to avoid confusion

**Comment by zhengj2007** [comment]
I think we can archive or remove the repository. The README indicated it has be merged to IAO repo.

**Comment by zhengj2007** [comment]
Archived the information-artifact-ontology/iao-releases repository
