### ISSUE TITLE
NTR: add 'ORCID identifier'

### ISSUE THREAD

**Issue by StroemPhi** [information-artifact-ontology/IAO#259]
There currently is the class [APOLLO_SV_00000496](http://purl.obolibrary.org/obo/APOLLO_SV_00000496) (ORCID) defined as:

> An identifier curated by ORCID, Inc. to denote some academic author.

Following the line of argumentation in https://github.com/ApolloDev/apollo-sv/issues/207, I propose to adopt this term into the IAO namespace with the following:

## Preferred term label

ORCID iD

## Synonyms

ORCID identifier, ORCID ID, ORCID id, iD, Open Researcher and Contributor ID

## Textual definition

A 'centrally registered identifier' that is issued by ORCID (https://orcid.org/) and used to persistantly identify oneself as a human researcher or contributor. "You can connect your iD with your professional information — affiliations, grants, publications, peer review, and more. You can use your iD to share your information with other systems, ensuring you get recognition for all your contributions, saving you time and hassle, and reducing the risk of errors." [https://orcid.org/]

## Suggested parent term

IAO:0000578 ('centrally registered identifier')

## Attribution

https://orcid.org/0000-0002-1595-3213

**Comment by hoganwr** [comment]
I don't understand Charles' comment, but I support IAO taking over the
class from Apollo-SV.

If these types of classes are thought to be problematic for whatever
reason, then I'd like to know what modeling pattern one should use to say
that an identifier is an ORCID, Twitter handle, GitHub user id, Scopus ID,
UF ID, etc, etc.  You could individually connect in the data every instance
of an ORCID to an individual representing the ORCID "system" or "site".
That would entail one extra triple per identifier...

**Comment by StroemPhi** [comment]
I'm leaving the Bioregistry comment asside to reduce the complextiy for now. (sorry @cthoyt) 

I would also like to know which is the best pattern to use when saying a certain identifier is used to denote a thing. 

I think the main problem one can run into is rooted in the fact that we commonly conflate the signifier with the signified in certain contexts to make things easier. If, for example, I were to use my ORCID in an annotation property as a means to express that I'm the creator of the ontology term with that annotation property (e.g. `IAO:ORCID dc:creator ORCID:0000-0002-1595-3213`), there is no problem and everyone would know how to interpret this triple. But if I want to say in a knowledge graph that I, an instance of NCBITaxon:'Homo Sapiens', participate in some planned process and would use my ORCID as IRI for that particular me instance, I would run into a problem, once this knowledge graph is being combined with another knowledge graph in which my instance IRI is different and there exists a triple `other-me-instance-IRI IAO:'denoted by' ORCID:0000-0002-1595-3213`. In this case the reasoner would complain that ORCID:0000-0002-1595-3213 cannot be a NCBITaxon:'Homo Sapiens' at the same time as also being an IAO:'identifier'.

**Comment by zhengj2007** [comment]
@StroemPhi Do you want to add 'ORCID identifier' before the release?

**Comment by StroemPhi** [comment]
@zhengj2007 yes, I can do that and would take the next free ID in the edit file, or is there a ID range table somewhere that I'm not aware of?

**Comment by zhengj2007** [comment]
I don't think IAO has any ID range table except those assigned to PNO and D-act. The next free ID should be fine.

**Comment by zhengj2007** [comment]
@StroemPhi Since the requested term is added, the tracker need to be closed. But the issue you raised regarding CRID and CRID symbol is worth to discuss. Could you please submit a new tracker about it? Or you can submit it to OBI. Then it can be discussed in OBI call. Thanks!
