### ISSUE TITLE
Inverse of http://purl.obolibrary.org/obo/IAO_0100001 "replaced_by"

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/IAO#88]
_From [jbolle...@gmail.com](https://code.google.com/u/110721641858070357012/) on November 24, 2010 01:54:26_

Please indicate the label for the new term replaces Please provide a textual definition This is the inverse of replaced_by. Can be used to define which terms have been replaced by this this term. Please add an example of usage for that term GO:0000750 replaces GO:0000174
where 
GO:0000174 replaced_by GO:0000750 Please provide any additional information below. (e.g., proposed position in the IAO hierarchy) i.e. to the limit of my knowledge please add this to the OWL definitions.

\<owl:AnnotationProperty rdf:about="#replaces">
	\<owl:inverseOf rdf:resource="IAO_010000">
\</owl:AnnotationProperty>

Regards,
Jerven

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=88_

**Comment by zhengj2007** [comment]
_From [mcour...@gmail.com](https://code.google.com/u/116795168307825520406/) on January 06, 2011 16:20:31_

The property is actually labeled "term replaced by". Any objection to name the inverse "replaces term" to make it a bit more explicit?

**Comment by zhengj2007** [comment]
_From [alanruttenberg@gmail.com](https://code.google.com/u/alanruttenberg@gmail.com/) on February 03, 2011 04:25:08_

Annotation properties can't have (explicit) inverses in OWL. So the best that could be done would be to define the property and make sure that both directions were always explicitly asserted. However, not sure it is really needed as one can always query  it in sparql with only one direction asserted.

**Comment by zhengj2007** [comment]
_From [mcour...@gmail.com](https://code.google.com/u/116795168307825520406/) on February 03, 2011 09:21:57_

Based on above we decided to close this issue with no further action. Please add a comment if there is disagreement.

**Status:** WontFix  
  **Cc:** alanruttenberg

**Comment by jamesamcl** [comment]
Just adding a note that Dublin Core has both directions for this:

https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/replaces/
https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/isReplacedBy/

I think there are use cases for asserting replacement in the other direction (e.g. if you can't change the previous term definition, or if the previous term definition is not in your ontology)

**Comment by cmungall** [comment]
Replaces is essentially pop:hasaltid which we discourage
